import React from "react"
import { Checkbox } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/46ekGSoaClnTutKM5a09z4/Components?node-id=190-1341&t=LEeiQ9m1lPAV5eB0-4",
  {
    props: {
      type: figma.enum("type", {
        unchecked: "unchecked",
        checked: "checked",
        indeterminate: "indeterminate",
      }),
      state: figma.enum("state", {
        idle: "idle",
        hover: "hover",
        pressed: "pressed",
        focused: "focused",
        disabled: "disabled",
      }),
    },
    example: (props) => <Checkbox {...props} />,
  }
)
